const chractorData = [
    { id: 1, answer: '손흥민', ImageUrl: '/인물사진/손흥민.jpg' },
    { id: 2, answer: '카리나', ImageUrl: '/인물사진/카리나.jpg' },
    { id: 3, answer: '박지성', ImageUrl: '/인물사진/박지성.jpg' },
    { id: 4, answer: '이도현', ImageUrl: '/인물사진/이도현.jpg' },
    { id: 5, answer: '유재석', ImageUrl: '/인물사진/유재석.jpg' },
    { id: 6, answer: '김연경', ImageUrl: '/인물사진/김연경.jpg' },
    { id: 7, answer: '유연석', ImageUrl: '/인물사진/유연석.jpg' },
    { id: 8, answer: '아이유', ImageUrl: '/인물사진/아이유.jpg' },
    { id: 9, answer: '정국', ImageUrl: '/인물사진/정국.jpg' },
    { id: 10, answer: '최우식', ImageUrl: '/인물사진/최우식.jpg' },
    { id: 11, answer: '차승원', ImageUrl: '/인물사진/차승원.jpg' },
    { id: 12, answer: '아린', ImageUrl: '/인물사진/아린.jpg' },
    { id: 13, answer: '윈터', ImageUrl: '/인물사진/윈터.jpg' },
    { id: 14, answer: '하니', ImageUrl: '/인물사진/하니.jpg' },
    { id: 15, answer: '카이', ImageUrl: '/인물사진/카이.jpg' },
    { id: 16, answer: '백종원', ImageUrl: '/인물사진/백종원.jpg' },
    { id: 17, answer: '이정재', ImageUrl: '/인물사진/이정재.jpg' },
    { id: 18, answer: '고윤정', ImageUrl: '/인물사진/고윤정.jpg' },
    { id: 19, answer: '해원', ImageUrl: '/인물사진/해원.jpg' },
    { id: 20, answer: '영케이', ImageUrl: '/인물사진/영케이.jpg' },
    { id: 21, answer: '스윙스', ImageUrl: '/인물사진/스윙스.jpg' },

]
export default chractorData;